name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: 安装依赖：
        run: yarn
        
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # registry-url: https://registry.npmjs.org/ # 如果不配置将影响publish
          
      - name: Setup yarn

      # 运行构建脚本
      - name: Build VuePress site
        run: yarn docs:build
        
      - name: publish 成功通知
        run: echo "deploy success"
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
